/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>


#define RCC_BASE 0X40021000
#define GPIOA_BASE 0X40010800

#define  RCC_APB2ENR         *((volatile uint32_t *)(RCC_BASE + 0X18))
#define  GPIOA_CRH           *((volatile uint32_t *)(GPIOA_BASE + 0X04))
#define  GPIO_ODR            *((volatile uint32_t *)(GPIOA_BASE + 0X0C))


int main(void)
{


	RCC_APB2ENR |=1<<2;
	GPIOA_CRH &=0xff0fffff;
	GPIOA_CRH |=0X00200000;
	while (1)
	{
		int i=0;
		GPIO_ODR |=1<<13;
		for ( i=0;i<500;i++);
		GPIO_ODR &=~(1<<13);
		for ( i=0;i<500;i++);

	}
	return 0;
}
